version: 0.2
env:
  variables:
    PR_ID_TAG: ""
phases:
  pre_build:
    commands:
      # get the PR number from version env var, originally in the format "pr/2"
      - PR_ID_TAG=$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f 2)
      - echo getting PR ID... PR_ID_TAG = $PR_ID_TAG
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date` for github branch $CODEBUILD_SOURCE_VERSION
      # - docker build -f Dockerfile.prod -t pwa-pr-build:$PR_ID_TAG .
      # - docker tag pwa-pr-build:$PR_ID_TAG 276375911640.dkr.ecr.us-east-1.amazonaws.com/pwa-pr-build:$PR_ID_TAG
  post_build:
    commands:
      - echo build Docker image complete `date` for github branch $CODEBUILD_SOURCE_VERSION
      - echo push latest Docker images to ECR...
      # - docker push 276375911640.dkr.ecr.us-east-1.amazonaws.com/pwa-pr-build:$PR_ID_TAG
artifacts:
  files:
    - Dockerrun.aws.json
  name: pr-$(echo $CODEBUILD_SOURCE_VERSION | cut -d'/' -f 2)
  # base-directory: .codebuild
  # discard-paths: yes

